name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Setup .NET
      uses: actions/setup-dotnet@v6
      with:
        dotnet-version: |
            8.x
            6.x

    - name: Restore dependencies
      run: dotnet restore src/ByteAether.QueryLink.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release src/ByteAether.QueryLink.sln

    - name: Run tests
      continue-on-error: true
      run: dotnet test --no-build --verbosity normal --logger "trx" --configuration Release src/ByteAether.QueryLink.sln

    - name: Upload test results
      uses: actions/upload-artifact@v7
      with:
        name: test-results
        path: ./**/TestResults/**/*.trx